package com.hungteen.pvzmod.render;

import com.hungteen.pvzmod.entities.bullets.EntityBall;
import com.hungteen.pvzmod.entities.bullets.EntityButter;
import com.hungteen.pvzmod.entities.bullets.EntityCabbage;
import com.hungteen.pvzmod.entities.bullets.EntityKernel;
import com.hungteen.pvzmod.entities.bullets.EntityMelon;
import com.hungteen.pvzmod.entities.bullets.EntityPea;
import com.hungteen.pvzmod.entities.bullets.EntityPotato;
import com.hungteen.pvzmod.entities.bullets.EntityThorn;
import com.hungteen.pvzmod.entities.drops.EntityCoin;
import com.hungteen.pvzmod.entities.drops.EntityPlantFood;
import com.hungteen.pvzmod.entities.drops.EntitySun;
import com.hungteen.pvzmod.entities.npcs.EntityCrazyDave;
import com.hungteen.pvzmod.entities.npcs.EntityHim;
import com.hungteen.pvzmod.entities.npcs.EntityPanney;
import com.hungteen.pvzmod.entities.npcs.EntityTreeMan;
import com.hungteen.pvzmod.entities.plants.common.EntityCabbagePult;
import com.hungteen.pvzmod.entities.plants.common.EntityDoubleShooter;
import com.hungteen.pvzmod.entities.plants.common.EntityGatlingPea;
import com.hungteen.pvzmod.entities.plants.common.EntityKernelPult;
import com.hungteen.pvzmod.entities.plants.common.EntityMelonPult;
import com.hungteen.pvzmod.entities.plants.common.EntityPeaShooter;
import com.hungteen.pvzmod.entities.plants.common.EntitySplitPea;
import com.hungteen.pvzmod.entities.plants.common.EntityThreePeater;
import com.hungteen.pvzmod.entities.plants.defence.EntityNutWall;
import com.hungteen.pvzmod.entities.plants.defence.EntityPumpkin;
import com.hungteen.pvzmod.entities.plants.defence.EntityTallNut;
import com.hungteen.pvzmod.entities.plants.electricity.EntityLightningRod;
import com.hungteen.pvzmod.entities.plants.explosion.EntityCherryBomb;
import com.hungteen.pvzmod.entities.plants.explosion.EntityPotatoMine;
import com.hungteen.pvzmod.entities.plants.fight.EntitySpikeRock;
import com.hungteen.pvzmod.entities.plants.fight.EntitySpikeWeed;
import com.hungteen.pvzmod.entities.plants.fight.EntitySquash;
import com.hungteen.pvzmod.entities.plants.fight.EntityTangleKelp;
import com.hungteen.pvzmod.entities.plants.flame.EntityJalapeno;
import com.hungteen.pvzmod.entities.plants.flame.EntityTorchWood;
import com.hungteen.pvzmod.entities.plants.ice.EntityIceShroom;
import com.hungteen.pvzmod.entities.plants.ice.EntityIcebergLettuce;
import com.hungteen.pvzmod.entities.plants.ice.EntitySnowPea;
import com.hungteen.pvzmod.entities.plants.ice.EntityWinterMelon;
import com.hungteen.pvzmod.entities.plants.light.EntityGoldLeaf;
import com.hungteen.pvzmod.entities.plants.light.EntitySunFlower;
import com.hungteen.pvzmod.entities.plants.light.EntitySunShroom;
import com.hungteen.pvzmod.entities.plants.light.EntityTwinSunFlower;
import com.hungteen.pvzmod.entities.plants.magic.EntityCatTail;
import com.hungteen.pvzmod.entities.plants.magic.EntityCoffeeBean;
import com.hungteen.pvzmod.entities.plants.magic.EntityHypnoShroom;
import com.hungteen.pvzmod.entities.plants.magic.EntityMariGold;
import com.hungteen.pvzmod.entities.plants.magic.EntityStrangeCat;
import com.hungteen.pvzmod.entities.special.EntityGardenRake;
import com.hungteen.pvzmod.entities.zombies.EntityZomBoss;
import com.hungteen.pvzmod.entities.zombies.grassday.EntityBucketHeadZombie;
import com.hungteen.pvzmod.entities.zombies.grassday.EntityConeHeadZombie;
import com.hungteen.pvzmod.entities.zombies.grassday.EntityFlagZombie;
import com.hungteen.pvzmod.entities.zombies.grassday.EntityNormalZombie;
import com.hungteen.pvzmod.entities.zombies.grassday.EntityPoleZombie;
import com.hungteen.pvzmod.entities.zombies.grassnight.EntityBackupDancer;
import com.hungteen.pvzmod.entities.zombies.grassnight.EntityDancingZombie;
import com.hungteen.pvzmod.entities.zombies.grassnight.EntityFootballZombie;
import com.hungteen.pvzmod.entities.zombies.grassnight.EntityGigaFootballZombie;
import com.hungteen.pvzmod.entities.zombies.grassnight.EntityOldZombie;
import com.hungteen.pvzmod.entities.zombies.grassnight.EntityPaperZombie;
import com.hungteen.pvzmod.entities.zombies.grassnight.EntityScreenDoorZombie;
import com.hungteen.pvzmod.entities.zombies.grassnight.EntitySundayEditionZombie;
import com.hungteen.pvzmod.entities.zombies.grassnight.EntityTombStone;
import com.hungteen.pvzmod.entities.zombies.plantzombies.EntityGatlingPeaZombie;
import com.hungteen.pvzmod.entities.zombies.plantzombies.EntityJalapenoZombie;
import com.hungteen.pvzmod.entities.zombies.plantzombies.EntityNutWallZombie;
import com.hungteen.pvzmod.entities.zombies.plantzombies.EntityPeaShooterZombie;
import com.hungteen.pvzmod.entities.zombies.plantzombies.EntitySquashZombie;
import com.hungteen.pvzmod.entities.zombies.plantzombies.EntityTallNutZombie;
import com.hungteen.pvzmod.entities.zombies.poolday.EntityBobsle;
import com.hungteen.pvzmod.entities.zombies.poolday.EntityBobsleZombie;
import com.hungteen.pvzmod.entities.zombies.poolday.EntityDolphinRider;
import com.hungteen.pvzmod.entities.zombies.poolday.EntityLavaZombie;
import com.hungteen.pvzmod.entities.zombies.poolday.EntitySnorkelZombie;
import com.hungteen.pvzmod.entities.zombies.poolday.EntityZomboni;
import com.hungteen.pvzmod.entities.zombies.poolnight.EntityBalloonZombie;
import com.hungteen.pvzmod.entities.zombies.poolnight.EntityDiggerZombie;
import com.hungteen.pvzmod.entities.zombies.poolnight.EntityJackInBoxZombie;
import com.hungteen.pvzmod.entities.zombies.poolnight.EntityPogoZombie;
import com.hungteen.pvzmod.entities.zombies.poolnight.EntityYetiZombie;
import com.hungteen.pvzmod.entities.zombies.roof.EntityCataPultZombie;
import com.hungteen.pvzmod.entities.zombies.roof.EntityGargantuar;
import com.hungteen.pvzmod.entities.zombies.roof.EntityImp;
import com.hungteen.pvzmod.entities.zombies.roof.EntitySadGargantuar;
import com.hungteen.pvzmod.entities.zombies.special.EntityBalloon;
import com.hungteen.pvzmod.entities.zombies.special.EntityDolphin;
import com.hungteen.pvzmod.entities.zombies.special.EntityDuckyTube;
import com.hungteen.pvzmod.entities.zombies.special.EntityElementBall;
import com.hungteen.pvzmod.entities.zombies.special.EntityJackOutBoxZombie;
import com.hungteen.pvzmod.registry.ItemRegister;
import com.hungteen.pvzmod.render.entities.bullets.RenderBall;
import com.hungteen.pvzmod.render.entities.bullets.RenderButter;
import com.hungteen.pvzmod.render.entities.bullets.RenderCabbage;
import com.hungteen.pvzmod.render.entities.bullets.RenderKernel;
import com.hungteen.pvzmod.render.entities.bullets.RenderMelon;
import com.hungteen.pvzmod.render.entities.bullets.RenderPea;
import com.hungteen.pvzmod.render.entities.bullets.RenderPotato;
import com.hungteen.pvzmod.render.entities.bullets.RenderThorn;
import com.hungteen.pvzmod.render.entities.drops.RenderCoin;
import com.hungteen.pvzmod.render.entities.drops.RenderPlantFood;
import com.hungteen.pvzmod.render.entities.drops.RenderSun;
import com.hungteen.pvzmod.render.entities.npcs.RenderCrazyDave;
import com.hungteen.pvzmod.render.entities.npcs.RenderHim;
import com.hungteen.pvzmod.render.entities.npcs.RenderPanney;
import com.hungteen.pvzmod.render.entities.npcs.RenderTreeMan;
import com.hungteen.pvzmod.render.entities.plants.common.RenderCabbagePult;
import com.hungteen.pvzmod.render.entities.plants.common.RenderDoubleShooter;
import com.hungteen.pvzmod.render.entities.plants.common.RenderGatlingPea;
import com.hungteen.pvzmod.render.entities.plants.common.RenderKernelPult;
import com.hungteen.pvzmod.render.entities.plants.common.RenderMelonPult;
import com.hungteen.pvzmod.render.entities.plants.common.RenderPeaShooter;
import com.hungteen.pvzmod.render.entities.plants.common.RenderSplitPea;
import com.hungteen.pvzmod.render.entities.plants.common.RenderThreePeater;
import com.hungteen.pvzmod.render.entities.plants.defence.RenderNutWall;
import com.hungteen.pvzmod.render.entities.plants.defence.RenderPumpkin;
import com.hungteen.pvzmod.render.entities.plants.defence.RenderTallNut;
import com.hungteen.pvzmod.render.entities.plants.electricity.RenderLightningRod;
import com.hungteen.pvzmod.render.entities.plants.explosion.RenderCherryBomb;
import com.hungteen.pvzmod.render.entities.plants.explosion.RenderPotatoMine;
import com.hungteen.pvzmod.render.entities.plants.fight.RenderSpikeRock;
import com.hungteen.pvzmod.render.entities.plants.fight.RenderSpikeWeed;
import com.hungteen.pvzmod.render.entities.plants.fight.RenderSquash;
import com.hungteen.pvzmod.render.entities.plants.fight.RenderTangleKelp;
import com.hungteen.pvzmod.render.entities.plants.flame.RenderJalapeno;
import com.hungteen.pvzmod.render.entities.plants.flame.RenderTorchWood;
import com.hungteen.pvzmod.render.entities.plants.ice.RenderIceShroom;
import com.hungteen.pvzmod.render.entities.plants.ice.RenderIcebergLettuce;
import com.hungteen.pvzmod.render.entities.plants.ice.RenderSnowPea;
import com.hungteen.pvzmod.render.entities.plants.ice.RenderWinterMelon;
import com.hungteen.pvzmod.render.entities.plants.light.RenderGoldLeaf;
import com.hungteen.pvzmod.render.entities.plants.light.RenderSunFlower;
import com.hungteen.pvzmod.render.entities.plants.light.RenderSunShroom;
import com.hungteen.pvzmod.render.entities.plants.light.RenderTwinSunFlower;
import com.hungteen.pvzmod.render.entities.plants.magic.RenderCatTail;
import com.hungteen.pvzmod.render.entities.plants.magic.RenderCoffeeBean;
import com.hungteen.pvzmod.render.entities.plants.magic.RenderHypnoShroom;
import com.hungteen.pvzmod.render.entities.plants.magic.RenderMariGold;
import com.hungteen.pvzmod.render.entities.plants.magic.RenderStrangeCat;
import com.hungteen.pvzmod.render.entities.special.RenderGardenRake;
import com.hungteen.pvzmod.render.entities.zombies.RenderZomBoss;
import com.hungteen.pvzmod.render.entities.zombies.grassday.RenderBucketHeadZombie;
import com.hungteen.pvzmod.render.entities.zombies.grassday.RenderConeHeadZombie;
import com.hungteen.pvzmod.render.entities.zombies.grassday.RenderFlagZombie;
import com.hungteen.pvzmod.render.entities.zombies.grassday.RenderNormalZombie;
import com.hungteen.pvzmod.render.entities.zombies.grassday.RenderPoleZombie;
import com.hungteen.pvzmod.render.entities.zombies.grassnight.RenderBackupDancer;
import com.hungteen.pvzmod.render.entities.zombies.grassnight.RenderDancingZombie;
import com.hungteen.pvzmod.render.entities.zombies.grassnight.RenderFootballZombie;
import com.hungteen.pvzmod.render.entities.zombies.grassnight.RenderGigaFootballZombie;
import com.hungteen.pvzmod.render.entities.zombies.grassnight.RenderOldZombie;
import com.hungteen.pvzmod.render.entities.zombies.grassnight.RenderPaperZombie;
import com.hungteen.pvzmod.render.entities.zombies.grassnight.RenderScreenDoorZombie;
import com.hungteen.pvzmod.render.entities.zombies.grassnight.RenderSundayEditionZombie;
import com.hungteen.pvzmod.render.entities.zombies.plantzombies.RenderGatlingPeaZombie;
import com.hungteen.pvzmod.render.entities.zombies.plantzombies.RenderJalapenoZombie;
import com.hungteen.pvzmod.render.entities.zombies.plantzombies.RenderNutWallZombie;
import com.hungteen.pvzmod.render.entities.zombies.plantzombies.RenderPeaShooterZombie;
import com.hungteen.pvzmod.render.entities.zombies.plantzombies.RenderSquashZombie;
import com.hungteen.pvzmod.render.entities.zombies.plantzombies.RenderTallNutZombie;
import com.hungteen.pvzmod.render.entities.zombies.poolday.RenderBobsle;
import com.hungteen.pvzmod.render.entities.zombies.poolday.RenderBobsleZombie;
import com.hungteen.pvzmod.render.entities.zombies.poolday.RenderDolphinRider;
import com.hungteen.pvzmod.render.entities.zombies.poolday.RenderLavaZombie;
import com.hungteen.pvzmod.render.entities.zombies.poolday.RenderSnorkelZombie;
import com.hungteen.pvzmod.render.entities.zombies.poolday.RenderZomboni;
import com.hungteen.pvzmod.render.entities.zombies.poolnight.RenderBalloonZombie;
import com.hungteen.pvzmod.render.entities.zombies.poolnight.RenderDiggerZombie;
import com.hungteen.pvzmod.render.entities.zombies.poolnight.RenderJackInBoxZombie;
import com.hungteen.pvzmod.render.entities.zombies.poolnight.RenderPogoZombie;
import com.hungteen.pvzmod.render.entities.zombies.poolnight.RenderYetiZombie;
import com.hungteen.pvzmod.render.entities.zombies.roof.RenderCataPultZombie;
import com.hungteen.pvzmod.render.entities.zombies.roof.RenderGargantuar;
import com.hungteen.pvzmod.render.entities.zombies.roof.RenderImp;
import com.hungteen.pvzmod.render.entities.zombies.roof.RenderSadGargantuar;
import com.hungteen.pvzmod.render.entities.zombies.special.RenderBalloon;
import com.hungteen.pvzmod.render.entities.zombies.special.RenderDolphin;
import com.hungteen.pvzmod.render.entities.zombies.special.RenderDuckyTube;
import com.hungteen.pvzmod.render.entities.zombies.special.RenderElementBall;
import com.hungteen.pvzmod.render.entities.zombies.special.RenderJackOutBoxZombie;
import com.hungteen.pvzmod.render.entities.zombies.special.RenderTombStone;

import net.minecraft.client.Minecraft;
import net.minecraft.init.Items;
import net.minecraftforge.fml.client.registry.RenderingRegistry;

public class RenderHandler {

	public static void registerEntityRenders()
	{
		RenderingRegistry.registerEntityRenderingHandler(EntityHim.class, m -> new RenderHim(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityNormalZombie.class, m -> new RenderNormalZombie(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityPeaShooter.class, m -> new RenderPeaShooter(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityPea.class, m -> new RenderPea(m, ItemRegister.PEA, Minecraft.getMinecraft().getRenderItem()));
		RenderingRegistry.registerEntityRenderingHandler(EntityDoubleShooter.class, m -> new RenderDoubleShooter(m));
		RenderingRegistry.registerEntityRenderingHandler(EntitySunFlower.class, m -> new RenderSunFlower(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityTreeMan.class, m -> new RenderTreeMan(m));
		RenderingRegistry.registerEntityRenderingHandler(EntitySun.class, m -> new RenderSun(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityNutWall.class, m -> new RenderNutWall(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityPotatoMine.class, m->new RenderPotatoMine(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityConeHeadZombie.class, m->new RenderConeHeadZombie(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityBucketHeadZombie.class, m->new RenderBucketHeadZombie(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityCabbagePult.class, m->new RenderCabbagePult(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityCabbage.class, m->new RenderCabbage(m,ItemRegister.CABBAGE, Minecraft.getMinecraft().getRenderItem()));
		RenderingRegistry.registerEntityRenderingHandler(EntityCoin.class, m->new RenderCoin(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityFlagZombie.class, m->new RenderFlagZombie(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityPlantFood.class, m->new RenderPlantFood(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityPotato.class, m->new RenderPotato(m,Items.POTATO,Minecraft.getMinecraft().getRenderItem()));
		RenderingRegistry.registerEntityRenderingHandler(EntitySnowPea.class, m->new RenderSnowPea(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityIcebergLettuce.class,m->new RenderIcebergLettuce(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityScreenDoorZombie.class, m->new RenderScreenDoorZombie(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityTorchWood.class, m->new RenderTorchWood(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityThreePeater.class, m->new RenderThreePeater(m));
		RenderingRegistry.registerEntityRenderingHandler(EntitySplitPea.class, m->new RenderSplitPea(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityFootballZombie.class, m->new RenderFootballZombie(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityGigaFootballZombie.class, m->new RenderGigaFootballZombie(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityJalapeno.class, m->new RenderJalapeno(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityJalapenoZombie.class, m->new RenderJalapenoZombie(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityCherryBomb.class, m->new RenderCherryBomb(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityCatTail.class, m->new RenderCatTail(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityThorn.class, m->new RenderThorn(m,ItemRegister.THORN,Minecraft.getMinecraft().getRenderItem()));
		RenderingRegistry.registerEntityRenderingHandler(EntityCrazyDave.class, m->new RenderCrazyDave(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityPoleZombie.class, m->new RenderPoleZombie(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityPeaShooterZombie.class, m->new RenderPeaShooterZombie(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityNutWallZombie.class, m->new RenderNutWallZombie(m));
		RenderingRegistry.registerEntityRenderingHandler(EntitySpikeWeed.class, m->new RenderSpikeWeed(m));
		RenderingRegistry.registerEntityRenderingHandler(EntitySquash.class, m->new RenderSquash(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityPaperZombie.class, m->new RenderPaperZombie(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityOldZombie.class, m->new RenderOldZombie(m));
		RenderingRegistry.registerEntityRenderingHandler(EntitySundayEditionZombie.class, m->new RenderSundayEditionZombie(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityDancingZombie.class, m->new RenderDancingZombie(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityBackupDancer.class, m->new RenderBackupDancer(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityMariGold.class, m->new RenderMariGold(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityZomboni.class, m->new RenderZomboni(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityBobsle.class, m->new RenderBobsle(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityBobsleZombie.class, m->new RenderBobsleZombie(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityKernelPult.class, m->new RenderKernelPult(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityButter.class, m->new RenderButter(m,ItemRegister.BUTTER,Minecraft.getMinecraft().getRenderItem()));
		RenderingRegistry.registerEntityRenderingHandler(EntityKernel.class, m->new RenderKernel(m,ItemRegister.KERNEL,Minecraft.getMinecraft().getRenderItem()));
		RenderingRegistry.registerEntityRenderingHandler(EntitySnorkelZombie.class, m->new RenderSnorkelZombie(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityLavaZombie.class, m->new RenderLavaZombie(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityDuckyTube.class, m->new RenderDuckyTube(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityGardenRake.class, m->new RenderGardenRake(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityTombStone.class, m->new RenderTombStone(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityLightningRod.class, m->new RenderLightningRod(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityDolphinRider.class, m->new RenderDolphinRider(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityDolphin.class, m->new RenderDolphin(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityIceShroom.class, m->new RenderIceShroom(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityPumpkin.class, m->new RenderPumpkin(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityTallNut.class, m->new RenderTallNut(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityTallNutZombie.class, m->new RenderTallNutZombie(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityTwinSunFlower.class, m->new RenderTwinSunFlower(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityTangleKelp.class, m->new RenderTangleKelp(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityBalloon.class, m->new RenderBalloon(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityBalloonZombie.class, m->new RenderBalloonZombie(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityGargantuar.class, m->new RenderGargantuar(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityImp.class, m->new RenderImp(m));
		RenderingRegistry.registerEntityRenderingHandler(EntitySadGargantuar.class, m->new RenderSadGargantuar(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityGoldLeaf.class, m->new RenderGoldLeaf(m));
		RenderingRegistry.registerEntityRenderingHandler(EntitySpikeRock.class, m->new RenderSpikeRock(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityZomBoss.class, m->new RenderZomBoss(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityElementBall.class, m->new RenderElementBall(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityJackInBoxZombie.class, m->new RenderJackInBoxZombie(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityJackOutBoxZombie.class, m->new RenderJackOutBoxZombie(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityMelonPult.class, m->new RenderMelonPult(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityMelon.class, m->new RenderMelon(m,ItemRegister.MELON,Minecraft.getMinecraft().getRenderItem()));
		RenderingRegistry.registerEntityRenderingHandler(EntityGatlingPea.class, m->new RenderGatlingPea(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityWinterMelon.class, m->new RenderWinterMelon(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityHypnoShroom.class, m->new RenderHypnoShroom(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityGatlingPeaZombie.class, m->new RenderGatlingPeaZombie(m));
		RenderingRegistry.registerEntityRenderingHandler(EntitySquashZombie.class, m->new RenderSquashZombie(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityCoffeeBean.class, m->new RenderCoffeeBean(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityPogoZombie.class, m->new RenderPogoZombie(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityYetiZombie.class, m->new RenderYetiZombie(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityCataPultZombie.class, m->new RenderCataPultZombie(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityBall.class, m->new RenderBall(m,ItemRegister.PEA,Minecraft.getMinecraft().getRenderItem()));
		RenderingRegistry.registerEntityRenderingHandler(EntityStrangeCat.class, m->new RenderStrangeCat(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityPanney.class, m->new RenderPanney(m));
		RenderingRegistry.registerEntityRenderingHandler(EntityDiggerZombie.class, m->new RenderDiggerZombie(m));
		RenderingRegistry.registerEntityRenderingHandler(EntitySunShroom.class, m->new RenderSunShroom(m));
	}
}
