package com.hungteen.pvzmod.util.enums;

public enum Zombies {
	//1
	NORMAL_ZOMBIE,
	FLAG_ZOMBIE,
	CONEHEAD_ZOMBIE,
	POLE_ZOMBIE,
	BUCKETHEAD_ZOMBIE,
	//2
	TOMB_STONE,
	PAPER_ZOMBIE,
	OLD_ZOMBIE,
	SUNDAY_EDITION_ZOMBIE, //boss 1
	SCREENDOOR_ZOMBIE,
	FOOTBALL_ZOMBIE,
	GIGA_FOOTBALL_ZOMBIE, //boss 2
	DANCING_ZOMBIE,       //boss 3
	BACKUP_DANCER,
	//3
	TOOL,
	SNORKEL_ZOMBIE,
	ZOMBONI,
	BOBSLE,
	BOBSLE_ZOMBIE,
	DOLPHIN_RIDER,
	LAVA_ZOMBIE,
	//4
	JACK_IN_BOX_ZOMBIE,
	BALLON_ZOMBIE,
	DIGGER_ZOMBIE,
	POGO_ZOMBIE,
	YETI_ZOMBIE,
	//5
	CATAPULT_ZOMBIE,
	GARGANTUAR,
	IMP,
	SAD_GARGANTUAR,
	//boss
	ZOMBOSS,
	//plant_zombie
	PEASHOOTER_ZOMBIE,
	NUTWALL_ZOMBIE,
	GATLINGPEA_ZOMBIE,
	TALLNUT_ZOMBIE,
	SQUASH_ZOMBIE,
	JALAPENO_ZOMBIE,
}
