package com.hungteen.pvzmod.util.enums;

public enum Zombies {
	NORMAL_ZOMBIE,
	FLAG_ZOMBIE,
	CONEHEAD_ZOMBIE,
	POLE_ZOMBIE,
	BUCKETHEAD_ZOMBIE,
	PAPER_ZOMBIE,
	OLD_ZOMBIE,
	SUNDAY_EDITION_ZOMBIE, //boss 1
	SCREENDOOR_ZOMBIE,
	FOOTBALL_ZOMBIE,
	GIGA_FOOTBALL_ZOMBIE, //boss 2
	DANCING_ZOMBIE, //boss 3
	BACKUP_DANCER,
	PEASHOOTER_ZOMBIE,
	NUTWALL_ZOMBIE,
	JALAPENO_ZOMBIE,
}
