package com.hungteen.pvz.utils.enums;

public enum Plants {
	// 1-1 ~ 1-10
	PEA_SHOOTER, SUN_FLOWER, CHERRY_BOMB, WALL_NUT, POTATO_MINE, SNOW_PEA, CHOMPER, REPEATER,
	// 2-1 ~ 2-10
	PUFF_SHROOM, SUN_SHROOM, FUME_SHROOM, GRAVE_BUSTER, HYPNO_SHROOM, SCAREDY_SHROOM, ICE_SHROOM, DOOM_SHROOM,
	// 3-1 ~ 3-10
	LILY_PAD, SQUASH, THREE_PEATER, TANGLE_KELP, JALAPENO, SPIKE_WEED, TORCH_WOOD, TALL_NUT,
	// 4-1 ~ 4-10
	SEA_SHROOM, PLANTERN, CACTUS, BLOVER, SPLIT_PEA, STAR_FRUIT, PUMPKIN, MAGNET_SHROOM,
	// 5-1 5-10
	CABBAGE_PULT, FLOWER_POT, KERNEL_PULT, COFFEE_BEAN, GARLIC, UMBRELLA_LEAF, MARIGOLD, MELON_PULT,
	// upgrate
	GATLING_PEA, TWIN_SUNFLOWER, GLOOM_SHROOM, CAT_TAIL, WINTER_MELON, GOLD_MAGNET, SPIKE_ROCK, COB_CANNON, IMITATER,
	// pvz2
	ICEBERG_LETTUCE, GOLD_LEAF,
	// other
	WATER_GUARD, LIGHTLING_ROD, STRANGE_CAT;

	public static Plants getPlantByName(String name) {
		for (Plants plant : Plants.values()) {
			if (name.equals(plant.toString().toLowerCase())) {
				return plant;
			}
		}
		return null;
	}

}
